name = "Valorium"
author = "Riser876 / GMalvestiti"
version = "0.16.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1ef4cd5a1945c10e3312f4c20c6f1f1559191ac7aa05dda2f59d5d93df69a06"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
