name = "Valorium"
author = "Riser876"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "439d670ff0324848d130b63ca0fd6a63b2a32fde5c967d81591e0191ccc2afbb"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
