name = "Valorium"
author = "Riser876 / GMalvestiti"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a317f974918344659a823fad6e892a8aa4ea06bc2a50efe74794b8ad9d97b245"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
