name = "Valorium"
author = "Riser876"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afe5d75efdb1a1ae5514c857bbb26bcfc43b1cbc0dfae45c7d0c6d642b37e64e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
