name = "Valorium"
author = "Riser876 / GMalvestiti"
version = "0.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90940f8a341df35d0e1f60c2886efebc2aab46aac8dd010a116f5e9b02012130"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
