name = "Valorium"
author = "Riser876 / GMalvestiti"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faac03b2dfe4594a356f68bb3cb65f2a21fd8d12f31c1fd8596cc79c5a69a0e2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
