name = "Valorium"
author = "Riser876"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fc28c0db36b7b6d89fd64bfea92965685a0d11b8fa206495c96fc2725724da0"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
