name = "Valorium"
author = "Riser876 / GMalvestiti"
version = "0.16.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5c71d73fd355fb6d7572ac6d9d45c7295dffdcfb0e2721f7369445802da5bd2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
