name = "Valorium"
author = "Riser876 / GMalvestiti"
version = "0.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a3af14eb19ebf159e8e71701ae763acd26bd165139bc48cf9272396577fda66"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
