name = "Valorium"
author = "Riser876"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11f506667630ed3d7dc94fc0683e17ec78920e793471e79627044c6145ee8a25"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
