name = "Valorium"
author = "Riser876"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baeff968383c23a7a4f2c06774a10d9ab786d5e33906a78c1ff26a2083669ddf"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
