name = "Valorium"
author = "Riser876 / GMalvestiti"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77b71683f0c50810d5753b8f9a5baf2b38b9dbb894f97b89d91da12dfa327537"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
